# Generated by Django 5.2 on 2025-04-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('description_long', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='produto_images/%Y/%m')),
                ('slug', models.SlugField(unique=True)),
                ('price_marketing', models.FloatField(default=0)),
                ('price_marketing_promotional', models.FloatField(default=0)),
                ('typej', models.CharField(choices=[('V', 'Variavel'), ('S', 'Simples')], default='V', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField(default=0)),
                ('price_promotional', models.FloatField(default=0)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
    ]
