# Generated by Django 5.2 on 2025-04-16 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_variation_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='variation',
            options={'verbose_name': 'Variação', 'verbose_name_plural': 'Variações'},
        ),
    ]
